### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wind91725** [NoviScl/XLNet_DREAM#2]
modeling_xlnet.py ,line 892 in forward
mems_mask = torch.zeros([data_mask.shape[0],men,bsz]).to(data_mask)

RuntimeError : sizes must be non=negative

**Comment by NoviScl** [comment]
Hi,

Are you using a GPU to run? May I know the full command you use and the complete log output?

**Comment by wind91725** [comment]
Hi，thank you for your reply. Here is full command and  complete log output .
On 08/6/2019 07:06，Chenglei<notifications@github.com> wrote：

Hi,

Are you using a GPU to run? May I know the full command you use and the complete log output?

**Comment by NoviScl** [comment]
Note: this issue has been solved by updating the versions to:
Python 3.6, Pytorch 1.0.1, cuda10
